const tree = [
  {
    nodeType: "element",
    nodeName: "body",
    style: {
      width: "375",
      height: "2000",
      backgroundImage:
        "blob:http://localhost:8080/f8e88b7e-244d-4d56-926e-09a05f502e89",
      paddingTop: "0",
      paddingRight: "0",
      paddingBottom: "0",
      paddingLeft: "0",
      marginTop: "0",
      marginRight: "0",
      marginBottom: "0",
      marginLeft: "0",
      display: "flex",
      flexDirection: "column",
      justifyContent: "flex-start",
      alignItems: "center",
      color: "#333",
      fontSize: "16",
      lineHeight: "20",
      fontWeight: "400",
      textAlign: "center",
    },
    childrenNodes: [
      {
        key: "content1686841846222",
        nodeType: "element",
        nodeName: "div",
        componentType: "LContent",
        innerText:
          "一年一度的圣诞节又来啦，这个圣诞虽然还是宅家，但有了这么多宅家的经验，即便不出门，也能营造出满满的圣诞氛围感，在家吃着火锅唱着歌看着电影一样乐呵呵！",
        width: "342.5",
        height: "158.5",
        childrenNodes: [{}],
        show: false,
        paddingTop: "690",
        innerPaddingTop: "26",
        innerPaddingRight: "17",
        innerpaddingBottom: "10",
        innerpaddingLeft: "25",
        backgroundImage:
          "blob:http://localhost:8080/14391d63-617b-4c22-b057-0ca08d8406cf",
        color: "#FFFFFF",
        fontSize: "16",
        lineHeight: "24.5",
        fontWeight: 400,
        textAlign: "left",
        backgroundWidth: "342",
        backgroundHeight: "158",
      },
      {
        key: "title1686842153762",
        nodeType: "element",
        nodeName: "div",
        componentType: "LTitle",
        innerText: "《真爱至上》",
        width: "178",
        height: "65.5",
        childrenNodes: [{}],
        show: false,
        paddingTop: "0",
        innerPaddingTop: "31",
        fontSize: "19",
        color: "#FFFFFF",
        lineHeight: "27.51",
        fontWeight: 500,
        textAlign: "center",
        backgroundImage:
          "blob:http://localhost:8080/c7efb822-437d-42c4-9cbe-89e2cb7302d4",
        backgroundWidth: "178",
        backgroundHeight: "65.5",
        marginTop: "80",
      },
      {
        key: "title1686842295670",
        nodeType: "element",
        nodeName: "div",
        componentType: "LTitle",
        innerText: "圣诞节专属，百看不厌！",
        width: "",
        height: "",
        childrenNodes: [{}],
        show: false,
        backgroundImage: "",
        color: "#FFFFFF",
        marginTop: "30",
        marginBottom: "50",
        fontSize: "14",
        lineHeight: " 20.27",
        fontWeight: 500,
        textAlign: "center",
      },
      {
        key: "video1686842374658",
        nodeType: "element",
        nodeName: "div",
        componentType: "LVideo",
        innerText: "Video Inner Text",
        width: "",
        height: "",
        childrenNodes: [{}],
        show: false,
      },
      {
        key: "title1686842377988",
        nodeType: "element",
        nodeName: "div",
        componentType: "LTitle",
        innerText: "《小鬼当家》",
        width: "178",
        height: "65.5",
        childrenNodes: [{}],
        show: false,
        innerPaddingTop: "31",
        textAlign: "center",
        fontWeight: 500,
        lineHeight: "27.51",
        fontSize: "19",
        color: "#FFFFFF",
        backgroundImage:
          "blob:http://localhost:8080/d4fc73fd-87ab-4f0f-a924-c96749e4348e",
        backgroundWidth: "178",
        backgroundHeight: "65.5",
        marginTop: "40",
      },
      {
        key: "title1686842515456",
        nodeType: "element",
        nodeName: "div",
        componentType: "LTitle",
        innerText: "机智小鬼智斗两蠢贼!",
        width: "",
        height: "",
        childrenNodes: [{}],
        show: false,
        fontSize: "14",
        lineHeight: "20.27",
        fontWeight: 500,
        textAlign: "center",
        color: "#FFFFFF",
        marginTop: "30",
      },
      {
        key: "video1686842576236",
        nodeType: "element",
        nodeName: "div",
        componentType: "LVideo",
        innerText: "Video Inner Text",
        width: "",
        height: "",
        childrenNodes: [{}],
        show: false,
        marginTop: "25",
      },
      {
        key: "title1686842596292",
        nodeType: "element",
        nodeName: "div",
        componentType: "LTitle",
        innerText: "《克劳斯：圣诞节的秘密》",
        width: " 290",
        height: "65.5",
        childrenNodes: [{}],
        backgroundImage:
          "blob:http://localhost:8080/27b5b55b-6aff-460c-8d47-afe24e3083f4",
        backgroundWidth: " 290",
        innerPaddingTop: "31",
        backgroundHeight: "65.5",
        textAlign: "center",
        color: "#FFFFFF",
        fontSize: "19",
        lineHeight: "27.51",
        fontWeight: 500,
      },
      {
        key: "title1686842746113",
        nodeType: "element",
        nodeName: "div",
        componentType: "LTitle",
        innerText: "脑洞大开的动画电影，用爱鼓舞人心！",
        width: "",
        height: "",
        childrenNodes: [{}],
        show: false,
        marginTop: "15",
        marginBottom: "25",
        color: "#FFFFFF",
        fontSize: "14",
        lineHeight: "20.27",
        fontWeight: 500,
        textAlign: "center",
      },
      {
        key: "video1686842813350",
        nodeType: "element",
        nodeName: "div",
        componentType: "LVideo",
        innerText: "Video Inner Text",
        width: "",
        height: "",
        childrenNodes: [{}],
      },
      {
        key: "title1686842820083",
        nodeType: "element",
        nodeName: "div",
        componentType: "LTitle",
        innerText: "",
        width: "265",
        height: "39",
        childrenNodes: [{}],
        show: false,
        backgroundImage:
          "blob:http://localhost:8080/dc9a7cd1-d9d2-4a6b-9be7-5ba683cc0578",
        backgroundWidth: "265",
        backgroundHeight: "39",
        marginTop: "55",
      },
    ],
  },
];
